version: '3.8'

services:
  elasticsearch-6.4:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.3
    container_name: elasticsearch-6.4
    restart: unless-stopped
    ports:
      - '9200:9200'
      - '9300:9300'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
     - discovery.type=single-node
     - TAKE_FILE_OWNERSHIP=true
