version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
